/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Unit to split text
 *
 * * A: short mode
 * * B: middle mode
 * * C: long mode (default)
 */
export declare class SplitMode {
  static a(): number
  static b(): number
  static c(): number
}

/** Tokenizer class for tokenizing text into morphemes */
export declare class Tokenizer {
  /** create a new Tokenizer instance */
  constructor()
  /** tokenize text into morphemes */
  tokenize(text: string, mode?: number | undefined | null): NapiResult<Array<Morpheme>>
}

/**
 * Morpheme properties based on `sudachi::analysis::morpheme::Morpheme`,
 * some functions are converted to properties that can be used in JavaScript.
 */
export interface Morpheme {
  /** the begin index in bytes of the morpheme in the original text */
  begin: number
  /** the end index in bytes of the morpheme in the original text */
  end: number
  /** the codepoint offset of the morpheme begin in the original text */
  beginC: number
  /** the codepoint offset of the morpheme end in the original text */
  endC: number
  /** the index of this morpheme */
  index: number
  /** a substring of the original text which corresponds to the morpheme */
  surface: string
  /** the part of speech id */
  partOfSpeechId: number
  /** the part of speech of the morpheme */
  partOfSpeech: Array<string>
  /** the form normalizing inconsistent spellings and inflected forms */
  normalizedForm: string
  /** word's lemma and '終止形' in Japanese. */
  dictionaryForm: string
  /** Japanese syllabaries 'カタカナ' */
  readingForm: string
  /** dictionary id, -1 if the morpheme is oov */
  dictionaryId: number
}
